# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_auto_20191111_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='tweet_length',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
